name: Build container

on:
  push:
    branches-ignore:
      - main # covered by deploy-staging.yml

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: docker build .