name: Deploy to Prod (on-prem)
on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-2019
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: mbta/actions/build-push-ecr@v2
        id: build-push
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          docker-repo: ${{ secrets.DOCKER_REPO }}
  Deploy:
    needs: Build
    uses: mbta/workflows/.github/workflows/deploy-on-prem.yml@main
    with:
      app-name: screen-checker
      environment: prod
      on-prem-cluster: hsctd-prod-managers
      splunk-index: screens-prod-application
      task-cpu: 1.0
      task-memory: 1024M
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
